# docker-compose.yml
services:
  mariadb:
    image: mariadb
    hostname: dj_mariadb
    env_file:
      - .db.env
    command: --max-connections=1000 --max-allowed-packet=512M
    volumes:
      - ./dbdata:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    restart: on-failure
  domjudge:
    image: domjudge/domserver
    hostname: dj_domserver
    env_file:
      - .env
    environment:
      - CONTAINER_TIMEZONE=Asia/Jakarta
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - .:/domjudge:cached
    links:
      - mariadb:mariadb
    ports:
      - 80:80
    privileged: true
    depends_on:
      mariadb:
        condition: service_healthy
