# docker-compose.yml
services:
  mariadb:
    container_name: domjudge-db
    image: mariadb
    hostname: dj_mariadb
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    command: --max-connections=1000 --max-allowed-packet=512M
    volumes:
      - ./dbdata:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    restart: on-failure
  domjudge:
    container_name: domjudge-srv
    image: domjudge/domserver
    hostname: dj_domserver
    environment:
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - CONTAINER_TIMEZONE=Asia/Jakarta
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - .:/domjudge:cached
    links:
      - mariadb:mariadb
    ports:
      - 80:80
    privileged: true
    restart: on-failure
    depends_on:
      mariadb:
        condition: service_healthy
