- name: Deploy DOMJudge
  hosts: vps 
  vars:
    - clone_dir: "domjudge-docker"
    - shell_path: "{{ clone_dir }}/prepare-contest-env.sh"
  tasks:
    - name: Clone bccfilkom-cp domjudge-docker configuration
      git:
        repo: https://github.com/bccfilkom-cp/domjudge-docker.git
        clone: yes
        update: yes 
        force: yes
        dest: "{{ clone_dir }}"
    - name: Create .env file with vars from inventory
      copy:
        content: |
          DB_HOST="{{ domserver_db_host }}"
          DB_USERNAME="{{ domserver_db_username }}"
          DB_NAME="{{ domserver_db_name }}"
          DB_PASSWORD="{{ domserver_db_password }}"
          DB_ROOT_PASSWORD="{{ domserver_db_root_password }}"
        dest: ~/domjudge-docker/.env
        owner: "{{ ansible_user }}"
    - name: Filling needed variables in prepare script
      shell: |
        sed -i 's/{domserver_ip_address}/"{{ domserver_ip_address }}"/g' "{{ shell_path }}"
        sed -i 's/{domserver_ip_curl}/"{{ domserver_ip_curl }}"/g' "{{ shell_path }}"
        sed -i 's/{domserver_port}/"{{ domserver_port }}"/g' "{{ shell_path }}"
        sed -i 's/{num_of_judgehosts_needed}/{{ num_of_judgehosts_needed }}/g' "{{ shell_path }}"
        sed -i 's/{docker_judgehost_network}/"{{ docker_judgehost_network }}"/g' "{{ shell_path }}"
    - name: Deploy the server using prep contest script
      shell: |
        chmod +x ~/domjudge-docker/prepare-contest-env.sh
        cd ~/domjudge-docker
        ./prepare-contest-env.sh